name: Rollback to Previous Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to rollback to'
        required: true

jobs:
  validate_tag:
    uses: ./.github/workflows/shared-validate-tag.yml
    with:
      tag: ${{ github.event.inputs.tag }}
  rollback:
    name: Rollback Deploy
    uses: ./.github/workflows/shared-deploy-release.yml
    needs: validate_tag
    with:
      # Pass the release information as needed; you may need to fetch the release details
      # For demonstration, only the tag is passed. You may want to expand this.
      release_tag: ${{ github.event.inputs.tag }}
    secrets: inherit