on:
  workflow_dispatch:
    inputs:
      comment-body:
        description: 'Body of the comment to create'
        required: true
        default: 'This is a test comment'
        type: string
      comment-body-two:
        description: 'Body of the comment to create'
        required: true
        default: 'This is a test comment I need to update this'
        type: string
jobs:
  create-comment-one:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        id: create_comment
        uses: ./.github/workflows/shared-upsert-comment.yml
        with:
          comment-body: ${{ github.event.inputs.comment-body }}
          comment-title: Comment One Test Please Ignore
  create-comment-two:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        id: create_comment
        uses: ./.github/workflows/shared-upsert-comment.yml
        with:
          comment-body: ${{ github.event.inputs.comment-body-two }}
          comment-title: Comment Two Test Please Ignore