name: Pull Request Comment Test
on: 
  pull_request:
    branches:
      - main

jobs:
  output-event-name:
    runs-on: ubuntu-latest
    steps:
      - name: Output event name
        run: |
          echo "Event name = ${{ github.event_name }}"
          echo "Event payload = ${{ toJson(github.event) }}"
          echo "Event action = ${{ github.event.action }}"
          echo "Event ref = ${{ github.ref }}"
          echo "Event sha = ${{ github.sha }}"
      - name: Output variable into script
        uses: actions/github-script@v7
        with:
          script: |
            const eventName = github.event_name;
            const eventPayload = github.event;
            const eventAction = github.event.action;
            const eventRef = github.ref;
            const eventSha = github.sha;

            console.log(`Event name: ${eventName}`);
            console.log(`Event payload: ${JSON.stringify(eventPayload)}`);
            console.log(`Event action: ${eventAction}`);
            console.log(`Event ref: ${eventRef}`);
            console.log(`Event sha: ${eventSha}`);
  # create-comment-one:
  #   name: Create comment
  #   uses: ./.github/workflows/shared-upsert-comment.yml
  #   with:
  #     comment-body: "Tons of text\n ### and more here on the next line"
  #     comment-title: Comment One Test Please Ignore
  # create-comment-two:
  #   name: Create comment
  #   uses: ./.github/workflows/shared-upsert-comment.yml
  #   with:
  #     comment-body: |
  #       ## This is an even bigger comment
  #       ### with even more text
  #       ### and even more text
  #       ### and even more text

  #       --- 

  #       **Checklist**
  #       - [ ] Item 1
  #       - [ ] Item 2
  #       - [ ] Item 3

  #       ---

  #       **Notes**
  #       > Add any additional notes or context here.

  #       ---

  #       **Links**
  #       - [Documentation](https://example.com/docs)
  #       - [Related Issue](#)

  #       ---
  #     comment-title: Comment Two Test Please Ignore
    