name: Pull request to main
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/shared-upload-build.yml
    with:
      artifact_name: build-artifact
      artifact_path: build.tar.gz
  comment:
    uses: ./.github/workflows/shared-upsert-comment.yml
    with:
      comment-body: |
        The build artifact is available for download.
      comment-title: Build Artifact
      pr-number: ${{ github.event.pull_request.number }}
