name: Pull request to main
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/shared-upload-build.yml
    with:
      artifact_name: build-artifact
      artifact_path: build.tar.gz
