name: Rollback to Previous Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to rollback to'
        required: true

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag exists
        id: validate_tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = '${{ github.event.inputs.tag }}';
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`,
              });
              console.log(`Tag ${tag} exists.`);
            } catch (error) {
              core.setFailed(`Tag ${tag} does not exist.`);
            }
  rollback:
    name: Rollback Deploy
    uses: ./.github/workflows/shared-deploy-release.yml
    needs: validate_tag
    with:
      # Pass the release information as needed; you may need to fetch the release details
      # For demonstration, only the tag is passed. You may want to expand this.
      release_tag: ${{ github.event.inputs.tag }}
    secrets: inherit