name: Release and Deploy
on:
  release:
    types: [created]


jobs:
  release:
    name: Deploy release
    uses: ./.github/workflows/shared-deploy-release.yml
    secrets: inherit
    with:
      release_tag: ${{ github.event.release.tag_name }}
 